# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: true
connections:
  - driver: postgresql
    dataSourceName: postgres://x:aa332211@localhost/postgres
    # user: postgres
    # passwd: aa332211
    # proto: tcp
    # host: 172.17.0.2
    # port: 5432
    # dbName: postgres
