POST http://localhost:5010/user/register
content-type: application/json

{
	"account" : "test" , 
	"password" : "test" , 
	"origin" : "",
  "nickname": "abc"
}
POST http://localhost:5000/authorize/token
content-type: application/json

{
  "username" : "test" , 
  "password" : "test",
  "grant_type": "password",
  "client_id": "test",
  "client_secret": "test",
  "scope": "test"
}
GET http://localhost:5010/user/page
Authorization: Bearer 0c65b3cffe0d44debb6d24a2d10ed2de

GET http://localhost:5010/metrics

POST http://localhost:5010/user/validate
content-type: application/json

{
  "username": "admin",
  "password": "123"
}
