###
POST http://localhost:5000/user/register
content-type: application/json

{
	"account" : "test" , 
	"password" : "test" , 
	"origin" : "",
  "nickname": "abc"
}
###
POST http://localhost:5000/token
content-type: application/json

{
  "username" : "test" , 
  "password" : "test",
  "grant_type": "password",
  "client_id": "test",
  "client_secret": "test",
  "scope": "test"
}
###
GET http://localhost:5000/user/page
Authorization: Bearer a88bf723-6e46-476f-863e-855c230cc9e2
