server:
  port: 5000
  host: 0.0.0.0
  cors: 
    status: false
    origins: 
      - http://localhost:3000
  http_timeout: 60
database:
  category: postgres
  username: x
  password: aa332211
  host: localhost
  port: 5432
  db_name: postgres
  run_migrations: false
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
log:
  # level: trace
  level: debug,sqlx=debug
auth:
  status: true
  argon_salt: "randomsalt-x"
  token_secret: "randomsecret-x"
  token_expired: 86400
  ignore: 
    - /authorize
    - /authorize/token
